# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3a17146142f88536f93cf23c4c8d20a54db74a3c38e21abe26a48129c8825c0a7c930858514b21dca4254d12603ea4a85bae70e591548c4dc99b8c5a07cda3

test:
  secret_key_base: 2b1ea75d33efb1e125cd6b0cd6159ef1825fc1958db9d53ccaf938b6645217a690ccea22afc2ee8cfb341852fda0de47472d481b3be9931279504929994b9451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
